# Generated by Django 5.0.4 on 2024-07-21 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('nickname', models.CharField(default='사용자', max_length=50)),
                ('currentPoints', models.IntegerField(default=0)),
                ('week_score', models.IntegerField(default=0)),
                ('banner', models.URLField(blank=True, max_length=500)),
                ('title', models.TextField(default='초보 개발자')),
                ('tier', models.CharField(choices=[('stone', 'Stone'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='stone', max_length=30)),
                ('nextTier', models.CharField(blank=True, default='Silver', max_length=20)),
                ('levelUpPoints', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
