# Generated by Django 5.0.6 on 2024-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='banner',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='week_score',
            field=models.IntegerField(default=0),
        ),
    ]
