# Generated by Django 5.0.6 on 2024-07-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='tier',
            field=models.CharField(choices=[('stone', 'Stone'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='stone', max_length=30),
        ),
    ]
