# Generated by Django 5.0.4 on 2024-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_googleuser_tier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleuser',
            old_name='total_score',
            new_name='currentPoints',
        ),
        migrations.AddField(
            model_name='googleuser',
            name='levelUpPoints',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='nextTier',
            field=models.CharField(blank=True, default='Silver', max_length=20),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='nickname',
            field=models.CharField(default='사용자', max_length=50),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='title',
            field=models.TextField(default='초보 개발자'),
        ),
    ]
