# Generated by Django 5.0.6 on 2024-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_googleuser_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
