<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-21 17:12
=======
# Generated by Django 5.0.4 on 2024-07-21 17:13
>>>>>>> 4879f4f548370eaa120067bfcdc3fff55bf96203

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklymission',
            name='week_number',
        ),
    ]
