# Generated by Django 5.0.6 on 2024-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('nickname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(default=0)),
                ('week_score', models.IntegerField(default=0)),
                ('banner', models.URLField(blank=True, max_length=500)),
                ('title', models.TextField(default='')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
